runtime:
  cache_dir: ./.cache/antora

site:
  title: "Summit Connect Madrid - OpenShift Workshops"
  url: https://github.com/rhcs-workshops/summit-connect-madrid-openshift
  start_page: summit-connect-madrid-openshift::index.adoc

content:
  sources:
    # - url: ./
    #   start_path: documentation
    #Change to make url parameters work EX: USER
    - url: git@github.com:rhcs-workshops/summit-connect-madrid-openshift.git
      tags: []
      branches: [master]
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/atarazana/course-ui/releases/download/v0.1.12c/ui-bundle.zip #Change to make url parameters work EX: USER
    snapshot: true
  supplemental_files:
    - path: ./supplemental-ui
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

output:
  dir: ./gh-pages
